# Generated by Django 4.0.3 on 2022-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Classe', models.CharField(max_length=100)),
                ('Função', models.IntegerField()),
            ],
        ),
    ]
